"""
workspace_export_service.py — File export helpers for AI Workspace

Converts text/conversation content to:
  PDF   (reportlab)
  DOCX  (python-docx)
  PPTX  (python-pptx)
  XLSX  (xlsxwriter  — parses markdown tables)
"""

import io
import re
from logging_config import get_logger

logger = get_logger(__name__)


# ─────────────────────────────────────────────────────────────
# PDF
# ─────────────────────────────────────────────────────────────

def generate_pdf(content: str, title: str = "Document") -> bytes:
    """Render Markdown-ish text content into a PDF document using reportlab.

    Recognises ``#``/``##``/``###`` headings, ``-``/``*``/bullet lines, and
    ``1.``-style numbered lines; everything else becomes a plain paragraph.
    Inline ``**bold**``/``*italic*``/`` `code` `` markers are stripped (not
    rendered as formatting) via ``_strip_inline``, and text is XML-escaped
    via ``_esc_xml`` for safe inclusion in reportlab Paragraphs.

    Args:
        content: Raw text/Markdown-ish body to render, one block per line.
        title: Document title, rendered as the first (Title-style) paragraph.

    Returns:
        Raw PDF file bytes.
    """
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=inch, rightMargin=inch,
        topMargin=inch, bottomMargin=inch,
    )
    styles = getSampleStyleSheet()
    bullet_style = ParagraphStyle(
        "bullet", parent=styles["Normal"],
        leftIndent=16, spaceAfter=2,
    )

    story = [Paragraph(_esc_xml(title), styles["Title"]), Spacer(1, 0.25 * inch)]

    for line in content.split("\n"):
        s = line.strip()
        if not s:
            story.append(Spacer(1, 6))
        elif s.startswith("### "):
            story.append(Paragraph(_esc_xml(s[4:]), styles["Heading3"]))
        elif s.startswith("## "):
            story.append(Paragraph(_esc_xml(s[3:]), styles["Heading2"]))
        elif s.startswith("# "):
            story.append(Paragraph(_esc_xml(s[2:]), styles["Heading1"]))
        elif s.startswith(("- ", "* ", "• ")):
            story.append(Paragraph("• " + _esc_xml(_strip_inline(s[2:])), bullet_style))
        elif re.match(r"^\d+\.\s", s):
            story.append(Paragraph(_esc_xml(_strip_inline(re.sub(r"^\d+\.\s", "", s))), styles["Normal"]))
        else:
            story.append(Paragraph(_esc_xml(_strip_inline(s)), styles["Normal"]))

    doc.build(story)
    return buf.getvalue()


# ─────────────────────────────────────────────────────────────
# DOCX
# ─────────────────────────────────────────────────────────────

def generate_docx(content: str, title: str = "Document") -> bytes:
    """Render Markdown-ish text content into a DOCX document using python-docx.

    Same line-based block parsing as ``generate_pdf`` (headings, bullets,
    numbered lists, plain paragraphs), mapped onto Word heading levels and
    the built-in "List Bullet"/"List Number" paragraph styles.

    Args:
        content: Raw text/Markdown-ish body to render, one block per line.
        title: Document title, added as a level-0 (Title) heading.

    Returns:
        Raw DOCX file bytes.
    """
    from docx import Document as DocxDocument

    doc = DocxDocument()
    doc.add_heading(title, 0)

    for line in content.split("\n"):
        s = line.strip()
        if not s:
            doc.add_paragraph()
        elif s.startswith("### "):
            doc.add_heading(_strip_inline(s[4:]), 3)
        elif s.startswith("## "):
            doc.add_heading(_strip_inline(s[3:]), 2)
        elif s.startswith("# "):
            doc.add_heading(_strip_inline(s[2:]), 1)
        elif s.startswith(("- ", "* ", "• ")):
            doc.add_paragraph(_strip_inline(s[2:]), style="List Bullet")
        elif re.match(r"^\d+\.\s", s):
            doc.add_paragraph(_strip_inline(re.sub(r"^\d+\.\s", "", s)), style="List Number")
        else:
            doc.add_paragraph(_strip_inline(s))

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ─────────────────────────────────────────────────────────────
# PPTX
# ─────────────────────────────────────────────────────────────

def generate_pptx(content: str, title: str = "Presentation") -> bytes:
    """Render text content into a PPTX slide deck using python-pptx.

    Builds a title slide ("Generated by AI Workspace" subtitle) followed by
    one "Title and Content" slide per section parsed by ``_parse_slides``
    (sections are split on ``#``/``##`` headings). If no headings are found,
    falls back to a single slide titled ``title`` with up to 20 lines of
    content as bullet points. Each slide is capped at 12 bullet points
    (100 chars for the title, 200 chars per bullet).

    Args:
        content: Raw text/Markdown-ish body to convert into slides.
        title: Title used for the title slide and as the fallback slide title.

    Returns:
        Raw PPTX file bytes.
    """
    from pptx import Presentation

    prs = Presentation()

    # Title slide
    ts = prs.slides.add_slide(prs.slide_layouts[0])
    ts.shapes.title.text = title
    try:
        ts.placeholders[1].text = "Generated by AI Workspace"
    except Exception:
        pass

    slides_data = _parse_slides(content)
    if not slides_data:
        slides_data = [{"title": title,
                        "points": [l.strip() for l in content.split("\n") if l.strip()][:20]}]

    layout = prs.slide_layouts[1]  # Title and Content
    for sd in slides_data:
        slide = prs.slides.add_slide(layout)
        slide.shapes.title.text = sd["title"][:100]
        tf = slide.placeholders[1].text_frame
        tf.word_wrap = True
        tf.clear()
        for i, pt in enumerate(sd["points"][:12]):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            p.text = pt[:200]
            p.level = 0

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


def _parse_slides(content: str) -> list:
    """Split Markdown-ish content into slide dicts on ``#``/``##`` headings.

    Args:
        content: Raw text with optional ``#``/``##`` heading lines marking
            slide boundaries; non-heading, non-empty lines under a heading
            become bullet points (leading ``-``/``*``/bullet markers and
            inline formatting are stripped via ``_strip_inline``).

    Returns:
        List of ``{"title": str, "points": list[str]}`` dicts, one per
        heading found. Empty list if no headings are present.
    """
    slides, current = [], None
    for line in content.split("\n"):
        s = line.strip()
        if s.startswith("## ") or s.startswith("# "):
            if current:
                slides.append(current)
            current = {"title": s.lstrip("#").strip(), "points": []}
        elif current is not None and s:
            clean = _strip_inline(s.lstrip("-*• ").strip())
            if clean:
                current["points"].append(clean)
    if current:
        slides.append(current)
    return slides


# ─────────────────────────────────────────────────────────────
# XLSX
# ─────────────────────────────────────────────────────────────

def generate_xlsx(content: str, title: str = "Data") -> bytes:
    """Render content into an XLSX workbook using xlsxwriter.

    If ``content`` contains a Markdown pipe table (parsed by
    ``_parse_md_table``), each row becomes a worksheet row with the first
    row styled as a header; otherwise each line of ``content`` is written
    verbatim into column A.

    Args:
        content: Raw text, ideally containing a Markdown table (``| a | b |``
            rows, with a ``|---|---|`` divider row skipped automatically).
        title: Worksheet name (truncated to Excel's 31-character limit).

    Returns:
        Raw XLSX file bytes.
    """
    import xlsxwriter

    buf = io.BytesIO()
    wb = xlsxwriter.Workbook(buf, {"in_memory": True})
    ws = wb.add_worksheet(title[:31])

    hdr_fmt  = wb.add_format({"bold": True, "bg_color": "#4f46e5", "font_color": "#ffffff", "border": 1})
    cell_fmt = wb.add_format({"text_wrap": True, "valign": "top", "border": 1})

    rows = _parse_md_table(content)
    if rows:
        for r, row in enumerate(rows):
            for c, cell in enumerate(row):
                ws.write(r, c, cell, hdr_fmt if r == 0 else cell_fmt)
        ws.set_column(0, max(len(r) for r in rows) - 1, 22)
    else:
        for r, line in enumerate(content.split("\n")):
            ws.write(r, 0, line.rstrip())
        ws.set_column(0, 0, 80)

    wb.close()
    return buf.getvalue()


def _parse_md_table(content: str) -> list:
    """Parse Markdown pipe-table rows out of free-form text content.

    Args:
        content: Raw text that may contain lines of the form ``| a | b |``.
            Divider rows (cells matching ``^[-:]+$``, e.g. ``|---|---|``)
            are skipped. Cell text has inline Markdown formatting stripped
            via ``_strip_inline``.

    Returns:
        List of rows, each a list of cell strings. Empty list if no pipe
        table rows are found.
    """
    rows = []
    for line in content.split("\n"):
        s = line.strip()
        if s.startswith("|") and s.endswith("|"):
            cells = [c.strip() for c in s[1:-1].split("|")]
            if any(re.match(r"^[-:]+$", c) for c in cells):
                continue  # skip divider row
            rows.append([_strip_inline(c) for c in cells])
    return rows


# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────

def _strip_inline(text: str) -> str:
    """Strip inline Markdown emphasis/code markers (**bold**, *italic*, `code`, etc.), returning plain text."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"__(.+?)__",     r"\1", text)
    text = re.sub(r"\*(.+?)\*",     r"\1", text)
    text = re.sub(r"_(.+?)_",       r"\1", text)
    text = re.sub(r"`(.+?)`",       r"\1", text)
    return text.strip()


def _esc_xml(text: str) -> str:
    """Escape &, <, > for safe inclusion in reportlab Paragraph XML-ish markup."""
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;"))
